// This file is auto-generated by Visual Studio when you save the .resx file with Access Modifier: Public.
// If it does not exist or the namespace is incorrect, open Resources.resx in the designer, set Access Modifier to 'Public', and save.
// The namespace should be: namespace OpenCore_Office.Resources.Languages
// The class should be: public class Resources : ...
// No manual changes are needed unless the file is missing or the namespace is wrong.